version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into DockerHub
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo "Running flyway migrations"
      - > 
        docker run --rm 
        -v "$(pwd)/migrations/sql:/flyway/sql"
        -e FLYWAY_URL=$FLYWAY_URL 
        -e FLYWAY_USER=$FLYWAY_USER 
        -e FLYWAY_PASSWORD=$FLYWAY_PASSWORD 
        -e FLYWAY_DEFAULT_SCHEMA=flyway 
        -e FLYWAY_CONNECT_RETRIES=10 
        -e FLYWAY_LOCATIONS="filesystem:./sql" 
        -e FLYWAY_PLACEHOLDERS_USER_ID=$FLYWAY_PLACEHOLDERS_USER_ID 
        -e FLYWAY_PLACEHOLDERS_PREDICTION_APP_USER_PW=$FLYWAY_PLACEHOLDERS_PREDICTION_APP_USER_PW 
        -e FLYWAY_PLACEHOLDERS_REVISIT_PREDICTION_USER_PW=$FLYWAY_PLACEHOLDERS_REVISIT_PREDICTION_USER_PW 
        -e FLYWAY_PLACEHOLDERS_AUTH_SERVICE_USER_PW=$FLYWAY_PLACEHOLDERS_AUTH_SERVICE_USER_PW 
        flyway/flyway:9.15.1 migrate
