version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /docker/username
    DOCKER_PASSWORD: /docker/password

phases:
  install:
  runtime-versions:
    nodejs: 14
  commands:
    - npm i
    - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
  build:
    commands:
      - cd client
      - npx cypress run
  post_build:
    commands:
      - echo "Tests completed on $(date)"
